version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3  
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@1.3.0
  docker: circleci/docker@2.1.4

jobs:
    build-frontend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - restore_cache:
            keys: [frontend-build]
        - run:
            name: Build front-end
            command: |
              cd src/frontend
              npx browserslist@latest --update-db
              npm install
              npm run build
              exit 0
        - save_cache:
            paths: [frontend/node_modules]
            key: frontend-build
  
    build-backend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - restore_cache:
            keys: [backend-build]
        - run:
            name: Back-end build
            command: |
              cd src/backend
              npm install
              exit 0
        - save_cache:
            paths: [backend/node_modules]
            key: backend-build
    lint:
        docker:
            # Use the same Docker base as the project 
          - image: circleci/node:13.8.0
        steps:
            - checkout
            - run:
                name: install dependencies
                command: |
                    # Install hadolint
                    make install
            # run lint!
            - run:
                name: Linting docker file
                command: |
                    make lint 
 
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - docker/hadolint:
          dockerfiles: './Dockerfile'
          ignore-rules: 'DL4005,DL3008'
          trusted-registries: 'docker.io,my-company.com:5000'